<?php

use App\Http\Controllers\BahanTerpakaiController;
use App\Http\Controllers\DashboardSawnTimberController;
use App\Http\Controllers\HidupKBPerGroupController;
use App\Http\Controllers\KayuBulatHidupController;
use App\Http\Controllers\MutasiBarangJadiController;
use App\Http\Controllers\MutasiCCAkhirController;
use App\Http\Controllers\MutasiFingerJointController;
use App\Http\Controllers\MutasiKayuBulatController;
use App\Http\Controllers\MutasiKayuBulatV2Controller;
use App\Http\Controllers\MutasiKayuBulatKGController;
use App\Http\Controllers\MutasiKayuBulatKGV2Controller;
use App\Http\Controllers\MutasiLaminatingController;
use App\Http\Controllers\MutasiMouldingController;
use App\Http\Controllers\MutasiReprosesController;
use App\Http\Controllers\MutasiSandingController;
use App\Http\Controllers\MutasiHasilRacipController;
use App\Http\Controllers\MutasiSTController;
use App\Http\Controllers\PenerimaanKayuBulatBulananPerSupplierController;
use App\Http\Controllers\MutasiS4SController;
use App\Http\Controllers\SaldoKayuBulatController;
use App\Http\Controllers\StockOpnameKayuBulatController;
use App\Http\Controllers\LabelNyangkutController;
use App\Http\Controllers\RangkumanJlhLabelInputController;
use App\Http\Controllers\RekapPembelianKayuBulatController;
use App\Http\Controllers\WebAuthController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');
Route::get('/dashboard/sawn-timber', [DashboardSawnTimberController::class, 'index'])->name('dashboard.sawn-timber.index');
Route::get('/dashboard/sawn-timber/preview', [DashboardSawnTimberController::class, 'preview'])->name('dashboard.sawn-timber.preview');

Route::get('/reports/mutasi/barang-jadi', [MutasiBarangJadiController::class, 'index'])->name('reports.mutasi.barang-jadi.index');
Route::post('/reports/mutasi/barang-jadi/download', [MutasiBarangJadiController::class, 'download'])->name('reports.mutasi.barang-jadi.download');
Route::post('/reports/mutasi/barang-jadi/preview', [MutasiBarangJadiController::class, 'preview'])->name('reports.mutasi.barang-jadi.preview');
Route::get('/reports/mutasi/finger-joint', [MutasiFingerJointController::class, 'index'])->name('reports.mutasi.finger-joint.index');
Route::post('/reports/mutasi/finger-joint/download', [MutasiFingerJointController::class, 'download'])->name('reports.mutasi.finger-joint.download');
Route::post('/reports/mutasi/finger-joint/preview', [MutasiFingerJointController::class, 'preview'])->name('reports.mutasi.finger-joint.preview');
Route::get('/reports/mutasi/moulding', [MutasiMouldingController::class, 'index'])->name('reports.mutasi.moulding.index');
Route::post('/reports/mutasi/moulding/download', [MutasiMouldingController::class, 'download'])->name('reports.mutasi.moulding.download');
Route::post('/reports/mutasi/moulding/preview', [MutasiMouldingController::class, 'preview'])->name('reports.mutasi.moulding.preview');
Route::get('/reports/mutasi/laminating', [MutasiLaminatingController::class, 'index'])->name('reports.mutasi.laminating.index');
Route::post('/reports/mutasi/laminating/download', [MutasiLaminatingController::class, 'download'])->name('reports.mutasi.laminating.download');
Route::post('/reports/mutasi/laminating/preview', [MutasiLaminatingController::class, 'preview'])->name('reports.mutasi.laminating.preview');
Route::get('/reports/mutasi/sanding', [MutasiSandingController::class, 'index'])->name('reports.mutasi.sanding.index');
Route::post('/reports/mutasi/sanding/download', [MutasiSandingController::class, 'download'])->name('reports.mutasi.sanding.download');
Route::post('/reports/mutasi/sanding/preview', [MutasiSandingController::class, 'preview'])->name('reports.mutasi.sanding.preview');
Route::get('/reports/mutasi/s4s', [MutasiS4SController::class, 'index'])->name('reports.mutasi.s4s.index');
Route::post('/reports/mutasi/s4s/download', [MutasiS4SController::class, 'download'])->name('reports.mutasi.s4s.download');
Route::post('/reports/mutasi/s4s/preview', [MutasiS4SController::class, 'preview'])->name('reports.mutasi.s4s.preview');
Route::get('/reports/mutasi/st', [MutasiSTController::class, 'index'])->name('reports.mutasi.st.index');
Route::post('/reports/mutasi/st/download', [MutasiSTController::class, 'download'])->name('reports.mutasi.st.download');
Route::post('/reports/mutasi/st/preview', [MutasiSTController::class, 'preview'])->name('reports.mutasi.st.preview');
Route::get('/reports/mutasi/cca-akhir', [MutasiCCAkhirController::class, 'index'])->name('reports.mutasi.cca-akhir.index');
Route::post('/reports/mutasi/cca-akhir/download', [MutasiCCAkhirController::class, 'download'])->name('reports.mutasi.cca-akhir.download');
Route::post('/reports/mutasi/cca-akhir/preview', [MutasiCCAkhirController::class, 'preview'])->name('reports.mutasi.cca-akhir.preview');
Route::get('/reports/mutasi/reproses', [MutasiReprosesController::class, 'index'])->name('reports.mutasi.reproses.index');
Route::post('/reports/mutasi/reproses/download', [MutasiReprosesController::class, 'download'])->name('reports.mutasi.reproses.download');
Route::post('/reports/mutasi/reproses/preview', [MutasiReprosesController::class, 'preview'])->name('reports.mutasi.reproses.preview');
Route::get('/reports/mutasi/kayu-bulat', [MutasiKayuBulatController::class, 'index'])->name('reports.mutasi.kayu-bulat.index');
Route::post('/reports/mutasi/kayu-bulat/download', [MutasiKayuBulatController::class, 'download'])->name('reports.mutasi.kayu-bulat.download');
Route::post('/reports/mutasi/kayu-bulat/preview', [MutasiKayuBulatController::class, 'preview'])->name('reports.mutasi.kayu-bulat.preview');
Route::get('/reports/mutasi/kayu-bulat-v2', [MutasiKayuBulatV2Controller::class, 'index'])->name('reports.mutasi.kayu-bulat-v2.index');
Route::post('/reports/mutasi/kayu-bulat-v2/download', [MutasiKayuBulatV2Controller::class, 'download'])->name('reports.mutasi.kayu-bulat-v2.download');
Route::post('/reports/mutasi/kayu-bulat-v2/preview', [MutasiKayuBulatV2Controller::class, 'preview'])->name('reports.mutasi.kayu-bulat-v2.preview');
Route::get('/reports/mutasi/kayu-bulat-kgv2', [MutasiKayuBulatKGV2Controller::class, 'index'])->name('reports.mutasi.kayu-bulat-kgv2.index');
Route::post('/reports/mutasi/kayu-bulat-kgv2/download', [MutasiKayuBulatKGV2Controller::class, 'download'])->name('reports.mutasi.kayu-bulat-kgv2.download');
Route::post('/reports/mutasi/kayu-bulat-kgv2/preview', [MutasiKayuBulatKGV2Controller::class, 'preview'])->name('reports.mutasi.kayu-bulat-kgv2.preview');
Route::get('/reports/mutasi/kayu-bulat-kg', [MutasiKayuBulatKGController::class, 'index'])->name('reports.mutasi.kayu-bulat-kg.index');
Route::post('/reports/mutasi/kayu-bulat-kg/download', [MutasiKayuBulatKGController::class, 'download'])->name('reports.mutasi.kayu-bulat-kg.download');
Route::post('/reports/mutasi/kayu-bulat-kg/preview', [MutasiKayuBulatKGController::class, 'preview'])->name('reports.mutasi.kayu-bulat-kg.preview');
Route::get('/reports/kayu-bulat/saldo', [SaldoKayuBulatController::class, 'index'])->name('reports.kayu-bulat.saldo.index');
Route::post('/reports/kayu-bulat/saldo/download', [SaldoKayuBulatController::class, 'download'])->name('reports.kayu-bulat.saldo.download');
Route::post('/reports/kayu-bulat/saldo/preview', [SaldoKayuBulatController::class, 'preview'])->name('reports.kayu-bulat.saldo.preview');
Route::get('/reports/kayu-bulat/rekap-pembelian', [RekapPembelianKayuBulatController::class, 'index'])->name('reports.kayu-bulat.rekap-pembelian.index');
Route::get('/reports/kayu-bulat/rekap-pembelian/preview', [RekapPembelianKayuBulatController::class, 'preview'])->name('reports.kayu-bulat.rekap-pembelian.preview');
Route::get('/reports/kayu-bulat/penerimaan-bulanan-per-supplier', [PenerimaanKayuBulatBulananPerSupplierController::class, 'index'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier.index');
Route::post('/reports/kayu-bulat/penerimaan-bulanan-per-supplier/download', [PenerimaanKayuBulatBulananPerSupplierController::class, 'download'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier.download');
Route::post('/reports/kayu-bulat/penerimaan-bulanan-per-supplier/preview', [PenerimaanKayuBulatBulananPerSupplierController::class, 'preview'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier.preview');
Route::get('/reports/kayu-bulat/stock-opname', [StockOpnameKayuBulatController::class, 'index'])->name('reports.kayu-bulat.stock-opname.index');
Route::post('/reports/kayu-bulat/stock-opname/download', [StockOpnameKayuBulatController::class, 'download'])->name('reports.kayu-bulat.stock-opname.download');
Route::post('/reports/kayu-bulat/stock-opname/preview', [StockOpnameKayuBulatController::class, 'preview'])->name('reports.kayu-bulat.stock-opname.preview');
Route::get('/reports/kayu-bulat/hidup-per-group', [HidupKBPerGroupController::class, 'index'])->name('reports.kayu-bulat.hidup-per-group.index');
Route::post('/reports/kayu-bulat/hidup-per-group/download', [HidupKBPerGroupController::class, 'download'])->name('reports.kayu-bulat.hidup-per-group.download');
Route::post('/reports/kayu-bulat/hidup-per-group/preview', [HidupKBPerGroupController::class, 'preview'])->name('reports.kayu-bulat.hidup-per-group.preview');
Route::get('/reports/kayu-bulat/hidup', [KayuBulatHidupController::class, 'index'])->name('reports.kayu-bulat.hidup.index');
Route::post('/reports/kayu-bulat/hidup/download', [KayuBulatHidupController::class, 'download'])->name('reports.kayu-bulat.hidup.download');
Route::post('/reports/kayu-bulat/hidup/preview', [KayuBulatHidupController::class, 'preview'])->name('reports.kayu-bulat.hidup.preview');
Route::get('/reports/rangkuman-label-input', [RangkumanJlhLabelInputController::class, 'index'])->name('reports.rangkuman-label-input.index');
Route::post('/reports/rangkuman-label-input/download', [RangkumanJlhLabelInputController::class, 'download'])->name('reports.rangkuman-label-input.download');
Route::post('/reports/rangkuman-label-input/preview', [RangkumanJlhLabelInputController::class, 'preview'])->name('reports.rangkuman-label-input.preview');
Route::get('/reports/mutasi-hasil-racip', [MutasiHasilRacipController::class, 'index'])->name('reports.mutasi-hasil-racip.index');
Route::post('/reports/mutasi-hasil-racip/download', [MutasiHasilRacipController::class, 'download'])->name('reports.mutasi-hasil-racip.download');
Route::post('/reports/mutasi-hasil-racip/preview', [MutasiHasilRacipController::class, 'preview'])->name('reports.mutasi-hasil-racip.preview');
Route::get('/reports/label-nyangkut', [LabelNyangkutController::class, 'index'])->name('reports.label-nyangkut.index');
Route::post('/reports/label-nyangkut/download', [LabelNyangkutController::class, 'download'])->name('reports.label-nyangkut.download');
Route::post('/reports/label-nyangkut/preview', [LabelNyangkutController::class, 'preview'])->name('reports.label-nyangkut.preview');
Route::get('/reports/bahan-terpakai', [BahanTerpakaiController::class, 'index'])->name('reports.bahan-terpakai.index');
Route::post('/reports/bahan-terpakai/download', [BahanTerpakaiController::class, 'download'])->name('reports.bahan-terpakai.download');
Route::post('/reports/bahan-terpakai/preview', [BahanTerpakaiController::class, 'preview'])->name('reports.bahan-terpakai.preview');
Route::middleware('guest')->post('/login', [WebAuthController::class, 'login'])->name('web.login');
Route::middleware('auth')->post('/logout', [WebAuthController::class, 'logout'])->name('web.logout');
