<?php

use App\Http\Controllers\BahanTerpakaiController;
use App\Http\Controllers\BalokSudahSemprotController;
use App\Http\Controllers\DashboardSawnTimberController;
use App\Http\Controllers\HidupKBPerGroupController;
use App\Http\Controllers\HasilOutputRacipHarianController;
use App\Http\Controllers\KbKhususBangkangController;
use App\Http\Controllers\KayuBulatHidupController;
use App\Http\Controllers\MutasiBarangJadiController;
use App\Http\Controllers\MutasiCCAkhirController;
use App\Http\Controllers\MutasiFingerJointController;
use App\Http\Controllers\MutasiKayuBulatController;
use App\Http\Controllers\MutasiKayuBulatV2Controller;
use App\Http\Controllers\MutasiKayuBulatKGController;
use App\Http\Controllers\MutasiKayuBulatKGV2Controller;
use App\Http\Controllers\MutasiLaminatingController;
use App\Http\Controllers\MutasiMouldingController;
use App\Http\Controllers\MutasiReprosesController;
use App\Http\Controllers\MutasiSandingController;
use App\Http\Controllers\MutasiHasilRacipController;
use App\Http\Controllers\MutasiRacipDetailController;
use App\Http\Controllers\MutasiSTController;
use App\Http\Controllers\PenerimaanKayuBulatBulananPerSupplierController;
use App\Http\Controllers\PenerimaanKayuBulatPerSupplierBulananGrafikController;
use App\Http\Controllers\PenerimaanKayuBulatPerSupplierGroupController;
use App\Http\Controllers\PenerimaanStSawmillKgController;
use App\Http\Controllers\PerbandinganKbMasukPeriode1Dan2Controller;
use App\Http\Controllers\MutasiS4SController;
use App\Http\Controllers\SaldoKayuBulatController;
use App\Http\Controllers\StockSTBasahController;
use App\Http\Controllers\TargetMasukBBController;
use App\Http\Controllers\TargetMasukBBBulananController;
use App\Http\Controllers\TimelineKayuBulatHarianController;
use App\Http\Controllers\TimelineKayuBulatBulananController;
use App\Http\Controllers\UmurKayuBulatNonRambungController;
use App\Http\Controllers\StockRacipKayuLatController;
use App\Http\Controllers\StockOpnameKayuBulatController;
use App\Http\Controllers\LabelNyangkutController;
use App\Http\Controllers\LembarTallyHasilSawmillController;
use App\Http\Controllers\RangkumanJlhLabelInputController;
use App\Http\Controllers\RekapPembelianKayuBulatController;
use App\Http\Controllers\WebAuthController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');
Route::get('/dashboard/sawn-timber', [DashboardSawnTimberController::class, 'index'])->name('dashboard.sawn-timber.index');
Route::get('/dashboard/sawn-timber/preview', [DashboardSawnTimberController::class, 'preview'])->name('dashboard.sawn-timber.preview');
Route::match(['get', 'post'], '/dashboard/sawn-timber/download', [DashboardSawnTimberController::class, 'download'])->name('dashboard.sawn-timber.download');
Route::get('/reports/sawn-timber/stock-st-basah', [StockSTBasahController::class, 'index'])->name('reports.sawn-timber.stock-st-basah.index');
Route::post('/reports/sawn-timber/stock-st-basah/download', [StockSTBasahController::class, 'download'])->name('reports.sawn-timber.stock-st-basah.download');
Route::post('/reports/sawn-timber/stock-st-basah/preview-pdf', [StockSTBasahController::class, 'previewPdf'])->name('reports.sawn-timber.stock-st-basah.preview-pdf');
Route::post('/reports/sawn-timber/stock-st-basah/preview', [StockSTBasahController::class, 'preview'])->name('reports.sawn-timber.stock-st-basah.preview');
Route::get('/reports/sawn-timber/penerimaan-st-dari-sawmill-kg', [PenerimaanStSawmillKgController::class, 'index'])->name('reports.sawn-timber.penerimaan-st-dari-sawmill-kg.index');
Route::post('/reports/sawn-timber/penerimaan-st-dari-sawmill-kg/download', [PenerimaanStSawmillKgController::class, 'download'])->name('reports.sawn-timber.penerimaan-st-dari-sawmill-kg.download');
Route::post('/reports/sawn-timber/penerimaan-st-dari-sawmill-kg/preview-pdf', [PenerimaanStSawmillKgController::class, 'previewPdf'])->name('reports.sawn-timber.penerimaan-st-dari-sawmill-kg.preview-pdf');
Route::post('/reports/sawn-timber/penerimaan-st-dari-sawmill-kg/preview', [PenerimaanStSawmillKgController::class, 'preview'])->name('reports.sawn-timber.penerimaan-st-dari-sawmill-kg.preview');
Route::get('/reports/sawn-timber/lembar-tally-hasil-sawmill', [LembarTallyHasilSawmillController::class, 'index'])->name('reports.sawn-timber.lembar-tally-hasil-sawmill.index');
Route::post('/reports/sawn-timber/lembar-tally-hasil-sawmill/download', [LembarTallyHasilSawmillController::class, 'download'])->name('reports.sawn-timber.lembar-tally-hasil-sawmill.download');
Route::post('/reports/sawn-timber/lembar-tally-hasil-sawmill/preview-pdf', [LembarTallyHasilSawmillController::class, 'previewPdf'])->name('reports.sawn-timber.lembar-tally-hasil-sawmill.preview-pdf');
Route::post('/reports/sawn-timber/lembar-tally-hasil-sawmill/preview', [LembarTallyHasilSawmillController::class, 'preview'])->name('reports.sawn-timber.lembar-tally-hasil-sawmill.preview');

Route::get('/reports/mutasi/barang-jadi', [MutasiBarangJadiController::class, 'index'])->name('reports.mutasi.barang-jadi.index');
Route::post('/reports/mutasi/barang-jadi/download', [MutasiBarangJadiController::class, 'download'])->name('reports.mutasi.barang-jadi.download');
Route::post('/reports/mutasi/barang-jadi/preview', [MutasiBarangJadiController::class, 'preview'])->name('reports.mutasi.barang-jadi.preview');
Route::get('/reports/mutasi/finger-joint', [MutasiFingerJointController::class, 'index'])->name('reports.mutasi.finger-joint.index');
Route::post('/reports/mutasi/finger-joint/download', [MutasiFingerJointController::class, 'download'])->name('reports.mutasi.finger-joint.download');
Route::post('/reports/mutasi/finger-joint/preview', [MutasiFingerJointController::class, 'preview'])->name('reports.mutasi.finger-joint.preview');
Route::get('/reports/mutasi/moulding', [MutasiMouldingController::class, 'index'])->name('reports.mutasi.moulding.index');
Route::post('/reports/mutasi/moulding/download', [MutasiMouldingController::class, 'download'])->name('reports.mutasi.moulding.download');
Route::post('/reports/mutasi/moulding/preview', [MutasiMouldingController::class, 'preview'])->name('reports.mutasi.moulding.preview');
Route::get('/reports/mutasi/laminating', [MutasiLaminatingController::class, 'index'])->name('reports.mutasi.laminating.index');
Route::post('/reports/mutasi/laminating/download', [MutasiLaminatingController::class, 'download'])->name('reports.mutasi.laminating.download');
Route::post('/reports/mutasi/laminating/preview', [MutasiLaminatingController::class, 'preview'])->name('reports.mutasi.laminating.preview');
Route::get('/reports/mutasi/sanding', [MutasiSandingController::class, 'index'])->name('reports.mutasi.sanding.index');
Route::post('/reports/mutasi/sanding/download', [MutasiSandingController::class, 'download'])->name('reports.mutasi.sanding.download');
Route::post('/reports/mutasi/sanding/preview', [MutasiSandingController::class, 'preview'])->name('reports.mutasi.sanding.preview');
Route::get('/reports/mutasi/s4s', [MutasiS4SController::class, 'index'])->name('reports.mutasi.s4s.index');
Route::post('/reports/mutasi/s4s/download', [MutasiS4SController::class, 'download'])->name('reports.mutasi.s4s.download');
Route::post('/reports/mutasi/s4s/preview', [MutasiS4SController::class, 'preview'])->name('reports.mutasi.s4s.preview');
Route::get('/reports/mutasi/st', [MutasiSTController::class, 'index'])->name('reports.mutasi.st.index');
Route::post('/reports/mutasi/st/download', [MutasiSTController::class, 'download'])->name('reports.mutasi.st.download');
Route::post('/reports/mutasi/st/preview', [MutasiSTController::class, 'preview'])->name('reports.mutasi.st.preview');
Route::get('/reports/mutasi/cca-akhir', [MutasiCCAkhirController::class, 'index'])->name('reports.mutasi.cca-akhir.index');
Route::post('/reports/mutasi/cca-akhir/download', [MutasiCCAkhirController::class, 'download'])->name('reports.mutasi.cca-akhir.download');
Route::post('/reports/mutasi/cca-akhir/preview', [MutasiCCAkhirController::class, 'preview'])->name('reports.mutasi.cca-akhir.preview');
Route::get('/reports/mutasi/reproses', [MutasiReprosesController::class, 'index'])->name('reports.mutasi.reproses.index');
Route::post('/reports/mutasi/reproses/download', [MutasiReprosesController::class, 'download'])->name('reports.mutasi.reproses.download');
Route::post('/reports/mutasi/reproses/preview', [MutasiReprosesController::class, 'preview'])->name('reports.mutasi.reproses.preview');
Route::get('/reports/mutasi/kayu-bulat', [MutasiKayuBulatController::class, 'index'])->name('reports.mutasi.kayu-bulat.index');
Route::post('/reports/mutasi/kayu-bulat/download', [MutasiKayuBulatController::class, 'download'])->name('reports.mutasi.kayu-bulat.download');
Route::post('/reports/mutasi/kayu-bulat/preview', [MutasiKayuBulatController::class, 'preview'])->name('reports.mutasi.kayu-bulat.preview');
Route::get('/reports/mutasi/kayu-bulat-v2', [MutasiKayuBulatV2Controller::class, 'index'])->name('reports.mutasi.kayu-bulat-v2.index');
Route::post('/reports/mutasi/kayu-bulat-v2/download', [MutasiKayuBulatV2Controller::class, 'download'])->name('reports.mutasi.kayu-bulat-v2.download');
Route::post('/reports/mutasi/kayu-bulat-v2/preview', [MutasiKayuBulatV2Controller::class, 'preview'])->name('reports.mutasi.kayu-bulat-v2.preview');
Route::get('/reports/mutasi/kayu-bulat-kgv2', [MutasiKayuBulatKGV2Controller::class, 'index'])->name('reports.mutasi.kayu-bulat-kgv2.index');
Route::post('/reports/mutasi/kayu-bulat-kgv2/download', [MutasiKayuBulatKGV2Controller::class, 'download'])->name('reports.mutasi.kayu-bulat-kgv2.download');
Route::post('/reports/mutasi/kayu-bulat-kgv2/preview', [MutasiKayuBulatKGV2Controller::class, 'preview'])->name('reports.mutasi.kayu-bulat-kgv2.preview');
Route::get('/reports/mutasi/kayu-bulat-kg', [MutasiKayuBulatKGController::class, 'index'])->name('reports.mutasi.kayu-bulat-kg.index');
Route::post('/reports/mutasi/kayu-bulat-kg/download', [MutasiKayuBulatKGController::class, 'download'])->name('reports.mutasi.kayu-bulat-kg.download');
Route::post('/reports/mutasi/kayu-bulat-kg/preview', [MutasiKayuBulatKGController::class, 'preview'])->name('reports.mutasi.kayu-bulat-kg.preview');
Route::get('/reports/kayu-bulat/saldo', [SaldoKayuBulatController::class, 'index'])->name('reports.kayu-bulat.saldo.index');
Route::post('/reports/kayu-bulat/saldo/download', [SaldoKayuBulatController::class, 'download'])->name('reports.kayu-bulat.saldo.download');
Route::post('/reports/kayu-bulat/saldo/preview', [SaldoKayuBulatController::class, 'preview'])->name('reports.kayu-bulat.saldo.preview');
Route::get('/reports/kayu-bulat/rekap-pembelian', [RekapPembelianKayuBulatController::class, 'index'])->name('reports.kayu-bulat.rekap-pembelian.index');
Route::get('/reports/kayu-bulat/rekap-pembelian/preview', [RekapPembelianKayuBulatController::class, 'preview'])->name('reports.kayu-bulat.rekap-pembelian.preview');
Route::match(['get', 'post'], '/reports/kayu-bulat/rekap-pembelian/download', [RekapPembelianKayuBulatController::class, 'download'])->name('reports.kayu-bulat.rekap-pembelian.download');
Route::get('/reports/kayu-bulat/target-masuk-bb', [TargetMasukBBController::class, 'index'])->name('reports.kayu-bulat.target-masuk-bb.index');
Route::match(['get', 'post'], '/reports/kayu-bulat/target-masuk-bb/download', [TargetMasukBBController::class, 'download'])->name('reports.kayu-bulat.target-masuk-bb.download');
Route::get('/reports/kayu-bulat/target-masuk-bb/preview', [TargetMasukBBController::class, 'preview'])->name('reports.kayu-bulat.target-masuk-bb.preview');
Route::get('/reports/kayu-bulat/target-masuk-bb-bulanan', [TargetMasukBBBulananController::class, 'index'])->name('reports.kayu-bulat.target-masuk-bb-bulanan.index');
Route::match(['get', 'post'], '/reports/kayu-bulat/target-masuk-bb-bulanan/download', [TargetMasukBBBulananController::class, 'download'])->name('reports.kayu-bulat.target-masuk-bb-bulanan.download');
Route::get('/reports/kayu-bulat/target-masuk-bb-bulanan/preview', [TargetMasukBBBulananController::class, 'preview'])->name('reports.kayu-bulat.target-masuk-bb-bulanan.preview');
Route::get('/reports/stock-racip-kayu-lat', [StockRacipKayuLatController::class, 'index'])->name('reports.stock-racip-kayu-lat.index');
Route::match(['get', 'post'], '/reports/stock-racip-kayu-lat/download', [StockRacipKayuLatController::class, 'download'])->name('reports.stock-racip-kayu-lat.download');
Route::get('/reports/stock-racip-kayu-lat/preview', [StockRacipKayuLatController::class, 'preview'])->name('reports.stock-racip-kayu-lat.preview');
Route::get('/reports/hasil-output-racip-harian', [HasilOutputRacipHarianController::class, 'index'])->name('reports.hasil-output-racip-harian.index');
Route::post('/reports/hasil-output-racip-harian/download', [HasilOutputRacipHarianController::class, 'download'])->name('reports.hasil-output-racip-harian.download');
Route::post('/reports/hasil-output-racip-harian/preview', [HasilOutputRacipHarianController::class, 'preview'])->name('reports.hasil-output-racip-harian.preview');
Route::get('/reports/kayu-bulat/penerimaan-bulanan-per-supplier', [PenerimaanKayuBulatBulananPerSupplierController::class, 'index'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier.index');
Route::post('/reports/kayu-bulat/penerimaan-bulanan-per-supplier/download', [PenerimaanKayuBulatBulananPerSupplierController::class, 'download'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier.download');
Route::post('/reports/kayu-bulat/penerimaan-bulanan-per-supplier/preview', [PenerimaanKayuBulatBulananPerSupplierController::class, 'preview'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier.preview');
Route::get('/reports/kayu-bulat/penerimaan-bulanan-per-supplier-grafik', [PenerimaanKayuBulatPerSupplierBulananGrafikController::class, 'index'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier-grafik.index');
Route::post('/reports/kayu-bulat/penerimaan-bulanan-per-supplier-grafik/download', [PenerimaanKayuBulatPerSupplierBulananGrafikController::class, 'download'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier-grafik.download');
Route::post('/reports/kayu-bulat/penerimaan-bulanan-per-supplier-grafik/preview', [PenerimaanKayuBulatPerSupplierBulananGrafikController::class, 'preview'])->name('reports.kayu-bulat.penerimaan-bulanan-per-supplier-grafik.preview');
Route::get('/reports/kayu-bulat/penerimaan-per-supplier-group', [PenerimaanKayuBulatPerSupplierGroupController::class, 'index'])->name('reports.kayu-bulat.penerimaan-per-supplier-group.index');
Route::post('/reports/kayu-bulat/penerimaan-per-supplier-group/download', [PenerimaanKayuBulatPerSupplierGroupController::class, 'download'])->name('reports.kayu-bulat.penerimaan-per-supplier-group.download');
Route::post('/reports/kayu-bulat/penerimaan-per-supplier-group/preview', [PenerimaanKayuBulatPerSupplierGroupController::class, 'preview'])->name('reports.kayu-bulat.penerimaan-per-supplier-group.preview');
Route::get('/reports/kayu-bulat/stock-opname', [StockOpnameKayuBulatController::class, 'index'])->name('reports.kayu-bulat.stock-opname.index');
Route::post('/reports/kayu-bulat/stock-opname/download', [StockOpnameKayuBulatController::class, 'download'])->name('reports.kayu-bulat.stock-opname.download');
Route::post('/reports/kayu-bulat/stock-opname/preview', [StockOpnameKayuBulatController::class, 'preview'])->name('reports.kayu-bulat.stock-opname.preview');
Route::get('/reports/kayu-bulat/hidup-per-group', [HidupKBPerGroupController::class, 'index'])->name('reports.kayu-bulat.hidup-per-group.index');
Route::post('/reports/kayu-bulat/hidup-per-group/download', [HidupKBPerGroupController::class, 'download'])->name('reports.kayu-bulat.hidup-per-group.download');
Route::post('/reports/kayu-bulat/hidup-per-group/preview', [HidupKBPerGroupController::class, 'preview'])->name('reports.kayu-bulat.hidup-per-group.preview');
Route::get('/reports/kayu-bulat/hidup', [KayuBulatHidupController::class, 'index'])->name('reports.kayu-bulat.hidup.index');
Route::post('/reports/kayu-bulat/hidup/download', [KayuBulatHidupController::class, 'download'])->name('reports.kayu-bulat.hidup.download');
Route::post('/reports/kayu-bulat/hidup/preview', [KayuBulatHidupController::class, 'preview'])->name('reports.kayu-bulat.hidup.preview');
Route::get('/reports/kayu-bulat/perbandingan-kb-masuk-periode-1-dan-2', [PerbandinganKbMasukPeriode1Dan2Controller::class, 'index'])->name('reports.kayu-bulat.perbandingan-kb-masuk-periode-1-dan-2.index');
Route::post('/reports/kayu-bulat/perbandingan-kb-masuk-periode-1-dan-2/download', [PerbandinganKbMasukPeriode1Dan2Controller::class, 'download'])->name('reports.kayu-bulat.perbandingan-kb-masuk-periode-1-dan-2.download');
Route::post('/reports/kayu-bulat/perbandingan-kb-masuk-periode-1-dan-2/preview-pdf', [PerbandinganKbMasukPeriode1Dan2Controller::class, 'previewPdf'])->name('reports.kayu-bulat.perbandingan-kb-masuk-periode-1-dan-2.preview-pdf');
Route::post('/reports/kayu-bulat/perbandingan-kb-masuk-periode-1-dan-2/preview', [PerbandinganKbMasukPeriode1Dan2Controller::class, 'preview'])->name('reports.kayu-bulat.perbandingan-kb-masuk-periode-1-dan-2.preview');
Route::get('/reports/kayu-bulat/kb-khusus-bangkang', [KbKhususBangkangController::class, 'index'])->name('reports.kayu-bulat.kb-khusus-bangkang.index');
Route::post('/reports/kayu-bulat/kb-khusus-bangkang/download', [KbKhususBangkangController::class, 'download'])->name('reports.kayu-bulat.kb-khusus-bangkang.download');
Route::post('/reports/kayu-bulat/kb-khusus-bangkang/preview-pdf', [KbKhususBangkangController::class, 'previewPdf'])->name('reports.kayu-bulat.kb-khusus-bangkang.preview-pdf');
Route::post('/reports/kayu-bulat/kb-khusus-bangkang/preview', [KbKhususBangkangController::class, 'preview'])->name('reports.kayu-bulat.kb-khusus-bangkang.preview');
Route::get('/reports/kayu-bulat/balok-sudah-semprot', [BalokSudahSemprotController::class, 'index'])->name('reports.kayu-bulat.balok-sudah-semprot.index');
Route::post('/reports/kayu-bulat/balok-sudah-semprot/download', [BalokSudahSemprotController::class, 'download'])->name('reports.kayu-bulat.balok-sudah-semprot.download');
Route::post('/reports/kayu-bulat/balok-sudah-semprot/preview-pdf', [BalokSudahSemprotController::class, 'previewPdf'])->name('reports.kayu-bulat.balok-sudah-semprot.preview-pdf');
Route::post('/reports/kayu-bulat/balok-sudah-semprot/preview', [BalokSudahSemprotController::class, 'preview'])->name('reports.kayu-bulat.balok-sudah-semprot.preview');
Route::get('/reports/kayu-bulat/timeline-kayu-bulat-harian', [TimelineKayuBulatHarianController::class, 'index'])->name('reports.kayu-bulat.timeline-kayu-bulat-harian.index');
Route::post('/reports/kayu-bulat/timeline-kayu-bulat-harian/download', [TimelineKayuBulatHarianController::class, 'download'])->name('reports.kayu-bulat.timeline-kayu-bulat-harian.download');
Route::post('/reports/kayu-bulat/timeline-kayu-bulat-harian/preview-pdf', [TimelineKayuBulatHarianController::class, 'previewPdf'])->name('reports.kayu-bulat.timeline-kayu-bulat-harian.preview-pdf');
Route::post('/reports/kayu-bulat/timeline-kayu-bulat-harian/preview', [TimelineKayuBulatHarianController::class, 'preview'])->name('reports.kayu-bulat.timeline-kayu-bulat-harian.preview');
Route::get('/reports/kayu-bulat/timeline-kayu-bulat-bulanan', [TimelineKayuBulatBulananController::class, 'index'])->name('reports.kayu-bulat.timeline-kayu-bulat-bulanan.index');
Route::post('/reports/kayu-bulat/timeline-kayu-bulat-bulanan/download', [TimelineKayuBulatBulananController::class, 'download'])->name('reports.kayu-bulat.timeline-kayu-bulat-bulanan.download');
Route::post('/reports/kayu-bulat/timeline-kayu-bulat-bulanan/preview-pdf', [TimelineKayuBulatBulananController::class, 'previewPdf'])->name('reports.kayu-bulat.timeline-kayu-bulat-bulanan.preview-pdf');
Route::post('/reports/kayu-bulat/timeline-kayu-bulat-bulanan/preview', [TimelineKayuBulatBulananController::class, 'preview'])->name('reports.kayu-bulat.timeline-kayu-bulat-bulanan.preview');
Route::get('/reports/kayu-bulat/umur-kayu-bulat-non-rambung', [UmurKayuBulatNonRambungController::class, 'index'])->name('reports.kayu-bulat.umur-kayu-bulat-non-rambung.index');
Route::post('/reports/kayu-bulat/umur-kayu-bulat-non-rambung/download', [UmurKayuBulatNonRambungController::class, 'download'])->name('reports.kayu-bulat.umur-kayu-bulat-non-rambung.download');
Route::post('/reports/kayu-bulat/umur-kayu-bulat-non-rambung/preview', [UmurKayuBulatNonRambungController::class, 'preview'])->name('reports.kayu-bulat.umur-kayu-bulat-non-rambung.preview');
Route::get('/reports/rangkuman-label-input', [RangkumanJlhLabelInputController::class, 'index'])->name('reports.rangkuman-label-input.index');
Route::post('/reports/rangkuman-label-input/download', [RangkumanJlhLabelInputController::class, 'download'])->name('reports.rangkuman-label-input.download');
Route::post('/reports/rangkuman-label-input/preview', [RangkumanJlhLabelInputController::class, 'preview'])->name('reports.rangkuman-label-input.preview');
Route::get('/reports/mutasi-hasil-racip', [MutasiHasilRacipController::class, 'index'])->name('reports.mutasi-hasil-racip.index');
Route::post('/reports/mutasi-hasil-racip/download', [MutasiHasilRacipController::class, 'download'])->name('reports.mutasi-hasil-racip.download');
Route::post('/reports/mutasi-hasil-racip/preview', [MutasiHasilRacipController::class, 'preview'])->name('reports.mutasi-hasil-racip.preview');
Route::get('/reports/mutasi-racip-detail', [MutasiRacipDetailController::class, 'index'])->name('reports.mutasi-racip-detail.index');
Route::post('/reports/mutasi-racip-detail/download', [MutasiRacipDetailController::class, 'download'])->name('reports.mutasi-racip-detail.download');
Route::post('/reports/mutasi-racip-detail/preview', [MutasiRacipDetailController::class, 'preview'])->name('reports.mutasi-racip-detail.preview');
Route::get('/reports/label-nyangkut', [LabelNyangkutController::class, 'index'])->name('reports.label-nyangkut.index');
Route::post('/reports/label-nyangkut/download', [LabelNyangkutController::class, 'download'])->name('reports.label-nyangkut.download');
Route::post('/reports/label-nyangkut/preview', [LabelNyangkutController::class, 'preview'])->name('reports.label-nyangkut.preview');
Route::get('/reports/bahan-terpakai', [BahanTerpakaiController::class, 'index'])->name('reports.bahan-terpakai.index');
Route::post('/reports/bahan-terpakai/download', [BahanTerpakaiController::class, 'download'])->name('reports.bahan-terpakai.download');
Route::post('/reports/bahan-terpakai/preview', [BahanTerpakaiController::class, 'preview'])->name('reports.bahan-terpakai.preview');
Route::middleware('guest')->post('/login', [WebAuthController::class, 'login'])->name('web.login');
Route::middleware('auth')->post('/logout', [WebAuthController::class, 'logout'])->name('web.logout');
