<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="utf-8">
    <style>
        /* Bootstrap-like subset for mPDF-safe rendering */
        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            font-family: "DejaVu Sans", sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #212529;
            background: #ffffff;
        }

        .container {
            width: 100%;
            padding: 12px;
        }

        .card {
            border: 1px solid #dee2e6;
            border-radius: 6px;
        }

        .card-body {
            padding: 14px;
        }

        .mb-0 {
            margin-bottom: 0;
        }

        .mb-1 {
            margin-bottom: 4px;
        }

        .mb-2 {
            margin-bottom: 8px;
        }

        .mb-3 {
            margin-bottom: 12px;
        }

        .mb-4 {
            margin-bottom: 16px;
        }

        .text-muted {
            color: #6c757d;
        }

        .text-end {
            text-align: right;
        }

        .small {
            font-size: 11px;
        }

        .badge {
            display: inline-block;
            padding: 3px 8px;
            font-size: 10px;
            border-radius: 10px;
            color: #ffffff;
            background: #0d6efd;
            vertical-align: middle;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 4px;
        }

        .table-responsive {
            width: 100%;
        }

        .table th,
        .table td {
            border: 1px solid #d1d5db;
            padding: 8px;
            vertical-align: top;
        }

        .table thead th {
            background: #f8f9fa;
            font-weight: 700;
            text-align: left;
        }

        .table-striped tbody tr.table-zebra td {
            background: #f2f4f7;
        }

        .table-hover tbody tr:hover {
            background: #f4f8ff;
        }

        .number {
            text-align: right;
            white-space: nowrap;
        }

        .empty {
            text-align: center;
            padding: 16px;
            color: #6c757d;
        }

        .summary-box {
            margin-top: 12px;
            border: 1px solid #dee2e6;
            border-radius: 6px;
            padding: 10px 12px;
            background: #f8f9fa;
        }
    </style>
</head>

<body>
    @php($generatedByName = $generatedBy?->name ?? 'Sistem')
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h1 class="mb-1">Laporan Penjualan</h1>
                <p class="text-muted mb-1">
                    Periode: {{ $startDate }} s.d. {{ $endDate }}
                </p>
                <p class="text-muted mb-3">
                    Dicetak oleh {{ $generatedByName }} pada {{ $generatedAt->format('Y-m-d H:i:s') }}
                </p>

                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                @if (!empty($rows))
                                    @foreach (array_keys($rows[0]) as $header)
                                        <th>{{ str_replace('_', ' ', ucfirst($header)) }}</th>
                                    @endforeach
                                @else
                                    <th>Data</th>
                                @endif
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($rows as $row)
                                <tr class="{{ $loop->odd ? 'table-zebra' : '' }}">
                                    @foreach ($row as $key => $value)
                                        <td class="{{ $amountKey && $key === $amountKey ? 'number' : '' }}">
                                            {{ is_numeric($value) ? number_format((float) $value, 2, ',', '.') : $value }}
                                        </td>
                                    @endforeach
                                </tr>
                            @empty
                                <tr>
                                    <td class="empty">Tidak ada data penjualan pada periode ini.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                <div class="summary-box text-end">
                    <div><strong>Grand Total:</strong> {{ number_format((float) $grandTotal, 2, ',', '.') }}</div>
                </div>
                <p class="small text-muted text-end mb-0">
                    Generated by {{ $generatedByName }}
                </p>
            </div>
        </div>
    </div>

</body>

</html>
