<?php

return [

    // Laporan Seluruh Mutasi :
    'mutasi_barang_jadi' => [
        'database_connection' => env('MUTASI_BARANG_JADI_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_BARANG_JADI_REPORT_PROCEDURE', 'SP_Mutasi_BarangJadi'),
        'sub_stored_procedure' => env('MUTASI_BARANG_JADI_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_BarangJadi'),
        'call_syntax' => env('MUTASI_BARANG_JADI_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_BARANG_JADI_REPORT_QUERY'),
        'sub_query' => env('MUTASI_BARANG_JADI_SUB_REPORT_QUERY'),
    ],
    'mutasi_finger_joint' => [
        'database_connection' => env('MUTASI_FINGER_JOINT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_FINGER_JOINT_REPORT_PROCEDURE', 'SP_Mutasi_FingerJoint'),
        'sub_stored_procedure' => env('MUTASI_FINGER_JOINT_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_FingerJoint'),
        'call_syntax' => env('MUTASI_FINGER_JOINT_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_FINGER_JOINT_REPORT_QUERY'),
        'sub_query' => env('MUTASI_FINGER_JOINT_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_FINGER_JOINT_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_FINGER_JOINT_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_moulding' => [
        'database_connection' => env('MUTASI_MOULDING_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_MOULDING_REPORT_PROCEDURE', 'SP_Mutasi_Moulding'),
        'sub_stored_procedure' => env('MUTASI_MOULDING_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_Moulding'),
        'call_syntax' => env('MUTASI_MOULDING_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_MOULDING_REPORT_QUERY'),
        'sub_query' => env('MUTASI_MOULDING_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_MOULDING_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_MOULDING_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_laminating' => [
        'database_connection' => env('MUTASI_LAMINATING_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_LAMINATING_REPORT_PROCEDURE', 'SP_Mutasi_Laminating'),
        'sub_stored_procedure' => env('MUTASI_LAMINATING_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_Laminating'),
        'call_syntax' => env('MUTASI_LAMINATING_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_LAMINATING_REPORT_QUERY'),
        'sub_query' => env('MUTASI_LAMINATING_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_LAMINATING_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_LAMINATING_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_sanding' => [
        'database_connection' => env('MUTASI_SANDING_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_SANDING_REPORT_PROCEDURE', 'SP_Mutasi_Sanding'),
        'sub_stored_procedure' => env('MUTASI_SANDING_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_Sanding'),
        'call_syntax' => env('MUTASI_SANDING_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_SANDING_REPORT_QUERY'),
        'sub_query' => env('MUTASI_SANDING_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_SANDING_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_SANDING_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_s4s' => [
        'database_connection' => env('MUTASI_S4S_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_S4S_REPORT_PROCEDURE', 'SP_Mutasi_S4S'),
        'sub_stored_procedure' => env('MUTASI_S4S_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_S4S'),
        'call_syntax' => env('MUTASI_S4S_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_S4S_REPORT_QUERY'),
        'sub_query' => env('MUTASI_S4S_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_S4S_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_S4S_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_st' => [
        'database_connection' => env('MUTASI_ST_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_ST_REPORT_PROCEDURE', 'SP_Mutasi_ST'),
        'sub_stored_procedure' => env('MUTASI_ST_SUB_REPORT_PROCEDURE', ''),
        'call_syntax' => env('MUTASI_ST_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_ST_REPORT_QUERY'),
        'sub_query' => env('MUTASI_ST_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_ST_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_ST_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_cca_akhir' => [
        'database_connection' => env('MUTASI_CCA_AKHIR_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_CCA_AKHIR_REPORT_PROCEDURE', 'SP_Mutasi_CCAkhir'),
        'sub_stored_procedure' => env('MUTASI_CCA_AKHIR_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_CCAkhir'),
        'call_syntax' => env('MUTASI_CCA_AKHIR_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_CCA_AKHIR_REPORT_QUERY'),
        'sub_query' => env('MUTASI_CCA_AKHIR_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_CCA_AKHIR_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_CCA_AKHIR_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_reproses' => [
        'database_connection' => env('MUTASI_REPROSES_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_REPROSES_REPORT_PROCEDURE', 'SP_Mutasi_Reproses'),
        'sub_stored_procedure' => env('MUTASI_REPROSES_SUB_REPORT_PROCEDURE', 'SP_SubMutasi_Reproses'),
        'call_syntax' => env('MUTASI_REPROSES_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_REPROSES_REPORT_QUERY'),
        'sub_query' => env('MUTASI_REPROSES_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_REPROSES_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_REPROSES_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_kayu_bulat' => [
        'database_connection' => env('MUTASI_KAYU_BULAT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_KAYU_BULAT_REPORT_PROCEDURE', 'SP_Mutasi_KayuBulat'),
        'sub_stored_procedure' => env('MUTASI_KAYU_BULAT_SUB_REPORT_PROCEDURE', ''),
        'call_syntax' => env('MUTASI_KAYU_BULAT_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_KAYU_BULAT_REPORT_QUERY'),
        'sub_query' => env('MUTASI_KAYU_BULAT_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_kayu_bulat_v2' => [
        'database_connection' => env('MUTASI_KAYU_BULAT_V2_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_KAYU_BULAT_V2_REPORT_PROCEDURE', 'SP_Mutasi_KayuBulatV2'),
        'sub_stored_procedure' => env('MUTASI_KAYU_BULAT_V2_SUB_REPORT_PROCEDURE', ''),
        'call_syntax' => env('MUTASI_KAYU_BULAT_V2_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_KAYU_BULAT_V2_REPORT_QUERY'),
        'sub_query' => env('MUTASI_KAYU_BULAT_V2_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_V2_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_V2_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_kayu_bulat_kgv2' => [
        'database_connection' => env('MUTASI_KAYU_BULAT_KGV2_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_KAYU_BULAT_KGV2_REPORT_PROCEDURE', 'SP_Mutasi_KayuBulatKGV2'),
        'sub_stored_procedure' => env('MUTASI_KAYU_BULAT_KGV2_SUB_REPORT_PROCEDURE', ''),
        'call_syntax' => env('MUTASI_KAYU_BULAT_KGV2_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_KAYU_BULAT_KGV2_REPORT_QUERY'),
        'sub_query' => env('MUTASI_KAYU_BULAT_KGV2_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_KGV2_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_KGV2_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_kayu_bulat_kg' => [
        'database_connection' => env('MUTASI_KAYU_BULAT_KG_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_KAYU_BULAT_KG_REPORT_PROCEDURE', 'SP_Mutasi_KayuBulatKG'),
        'sub_stored_procedure' => env('MUTASI_KAYU_BULAT_KG_SUB_REPORT_PROCEDURE', ''),
        'call_syntax' => env('MUTASI_KAYU_BULAT_KG_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_KAYU_BULAT_KG_REPORT_QUERY'),
        'sub_query' => env('MUTASI_KAYU_BULAT_KG_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_KG_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_KAYU_BULAT_KG_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'mutasi_hasil_racip' => [
        'database_connection' => env('MUTASI_HASIL_RACIP_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('MUTASI_HASIL_RACIP_REPORT_PROCEDURE', 'SPWps_LapMutasiHasilRacip'),
        'call_syntax' => env('MUTASI_HASIL_RACIP_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('MUTASI_HASIL_RACIP_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('MUTASI_HASIL_RACIP_REPORT_EXPECTED_COLUMNS', '')))),
    ],

    // Kayu Bulat
    'saldo_kayu_bulat' => [
        'database_connection' => env('SALDO_KAYU_BULAT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('SALDO_KAYU_BULAT_REPORT_PROCEDURE', 'SPWps_LapSaldoKayuBulat'),
        'call_syntax' => env('SALDO_KAYU_BULAT_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('SALDO_KAYU_BULAT_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('SALDO_KAYU_BULAT_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'rekap_pembelian_kayu_bulat' => [
        'database_connection' => env('REKAP_PEMBELIAN_KAYU_BULAT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('REKAP_PEMBELIAN_KAYU_BULAT_REPORT_PROCEDURE', 'SPWps_LapRekapPembelianKayuBulat'),
        'call_syntax' => env('REKAP_PEMBELIAN_KAYU_BULAT_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('REKAP_PEMBELIAN_KAYU_BULAT_REPORT_QUERY'),
        'parameter_count' => (int) env('REKAP_PEMBELIAN_KAYU_BULAT_REPORT_PARAMETER_COUNT', 2),
    ],
    'penerimaan_kayu_bulat_bulanan_per_supplier' => [
        'database_connection' => env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_REPORT_PROCEDURE', 'SP_LaPenerimaanKayuBulatBulananPerSupplier'),
        'sub_stored_procedure' => env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_SUB_REPORT_PROCEDURE', 'SP_SubLaPenerimaanKayuBulatBulananPerSupplier'),
        'call_syntax' => env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_REPORT_QUERY'),
        'sub_query' => env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_SUB_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('PENERIMAAN_KAYU_BULAT_BULANAN_PER_SUPPLIER_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'stock_opname_kayu_bulat' => [
        'database_connection' => env('STOCK_OPNAME_KAYU_BULAT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env(
            'STOCK_OPNAME_KAYU_BULAT_REPORT_EXPECTED_COLUMNS',
            'NoKayuBulat,Tanggal,JenisKayu,Supplier,NoSuket,NoPlat,NoTruk,Tebal,Lebar,Panjang,Pcs,JmlhTon'
        )))),
    ],

    // Dashboard
    'dashboard_sawn_timber' => [
        'database_connection' => env('DASHBOARD_SAWN_TIMBER_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('DASHBOARD_SAWN_TIMBER_REPORT_PROCEDURE', 'SPWps_LapDashboardSawnTimber'),
        'call_syntax' => env('DASHBOARD_SAWN_TIMBER_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('DASHBOARD_SAWN_TIMBER_REPORT_QUERY'),
        'parameter_count' => (int) env('DASHBOARD_SAWN_TIMBER_REPORT_PARAMETER_COUNT', 2),
        'ctr_divisor' => (float) env('DASHBOARD_SAWN_TIMBER_CTR_DIVISOR', '75'),
        'type_order' => array_filter(array_map('trim', explode(',', (string) env(
            'DASHBOARD_SAWN_TIMBER_TYPE_ORDER',
            'JABON,JABON TG,KAYU LAT JABON,KAYU LAT RAMBUNG,PULAI,RAMBUNG - MC 1,RAMBUNG - MC 2,RAMBUNG - STD,SEMBARANG'
        )))),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('DASHBOARD_SAWN_TIMBER_REPORT_EXPECTED_COLUMNS', '')))),
    ],

    // Laporan Verifikasi :
    'rangkuman_jlh_label_input' => [
        'database_connection' => env('RANGKUMAN_LABEL_INPUT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('RANGKUMAN_LABEL_INPUT_REPORT_PROCEDURE', 'SPWps_LapRangkumanJlhLabelInput'),
        'call_syntax' => env('RANGKUMAN_LABEL_INPUT_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('RANGKUMAN_LABEL_INPUT_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('RANGKUMAN_LABEL_INPUT_REPORT_EXPECTED_COLUMNS', '')))),
    ],

    'label_nyangkut' => [
        'database_connection' => env('LABEL_NYANGKUT_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('LABEL_NYANGKUT_REPORT_PROCEDURE', 'SPWps_LapLabelNyangkut'),
        'call_syntax' => env('LABEL_NYANGKUT_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('LABEL_NYANGKUT_REPORT_QUERY'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('LABEL_NYANGKUT_REPORT_EXPECTED_COLUMNS', '')))),
    ],
    'bahan_terpakai' => [
        'database_connection' => env('BAHAN_TERPAKAI_REPORT_DB_CONNECTION', env('DB_CONNECTION')),
        'stored_procedure' => env('BAHAN_TERPAKAI_REPORT_PROCEDURE', 'SPWps_LapBahanTerpakai'),
        'sub_stored_procedure' => env('BAHAN_TERPAKAI_SUB_REPORT_PROCEDURE', 'SPWps_LapSubBahanTerpakai'),
        'call_syntax' => env('BAHAN_TERPAKAI_REPORT_CALL_SYNTAX', 'exec'),
        'query' => env('BAHAN_TERPAKAI_REPORT_QUERY'),
        'sub_query' => env('BAHAN_TERPAKAI_SUB_REPORT_QUERY'),
        'ton_to_m3_factor' => (float) env('BAHAN_TERPAKAI_TON_TO_M3_FACTOR', '1.416'),
        'expected_columns' => array_filter(array_map('trim', explode(',', (string) env('BAHAN_TERPAKAI_REPORT_EXPECTED_COLUMNS', '')))),
        'expected_sub_columns' => array_filter(array_map('trim', explode(',', (string) env('BAHAN_TERPAKAI_SUB_REPORT_EXPECTED_COLUMNS', '')))),
    ],


    // Pengaturan otentikasi JWT untuk endpoint laporan
    'report_auth' => [
        'issuers' => array_filter(array_map('trim', explode(',', (string) env('REPORT_JWT_TRUSTED_ISSUERS', env('REPORT_JWT_TRUSTED_ISSUER', ''))))),
        'audiences' => array_filter(array_map('trim', explode(',', (string) env('REPORT_JWT_TRUSTED_AUDIENCES', env('REPORT_JWT_TRUSTED_AUDIENCE', ''))))),
        'required_scope' => env('REPORT_JWT_REQUIRED_SCOPE'),
        'scope_claim' => env('REPORT_JWT_SCOPE_CLAIM', 'scope'),
        'issued_audience' => env('REPORT_JWT_ISSUED_AUDIENCE'),
        'issued_scope' => env('REPORT_JWT_ISSUED_SCOPE'),
        'subject_claim' => env('REPORT_JWT_SUBJECT_CLAIM', 'sub'),
        'name_claim' => env('REPORT_JWT_NAME_CLAIM', 'name'),
        'email_claim' => env('REPORT_JWT_EMAIL_CLAIM', 'email'),
    ],
];
