<?php

return [
    'label' => 'Sales',
    'xml_source' => 'RU/Sales/Sales Invoice.xml',
    'record_tag' => 'Invoice',
    'sub_reports' => [
        'sales_invoice' => [
            'label' => 'Sales Invoice (RU)',
            'columns' => [
                'InvoiceID' => 'Invoice ID',
                'InvoiceNumber' => 'No SI',
                'InvoiceDate' => 'Tgl Faktur',
                'CustomerName' => 'Customer',
                'AddressLine1' => 'Alamat Customer 1',
                'AddressLine2' => 'Alamat Customer 2',
                'City' => 'Kota',
                'BillingAddressLine1' => 'Alamat Tagih 1',
                'BillingAddressLine2' => 'Alamat Tagih 2',
                'BillingCity' => 'Kota Tagih',
                'ShippingAddressLine1' => 'Alamat Kirim 1',
                'ShippingAddressLine2' => 'Alamat Kirim 2',
                'ShippingCity' => 'Kota Kirim',
                'DONo' => 'No DO',
                'InvoiceDueDate' => 'Tgl Kirim',
                'PaymentTerm' => 'Jatuh Tempo',
                'SalesPersonName' => 'Salesman',
                'VehicleNo' => 'No Kendaraan',
                'Remarks' => 'Keterangan',
                'Createdby' => 'Dibuat Oleh',
                'ItemCode' => 'Kode Barang',
                'ItemName' => 'Nama Barang',
                'Quantity' => 'Qty',
                'UOMCode' => 'Satuan',
                'Price' => 'Harga',
                'ItemDiscount' => 'Disc',
                'LineTotal' => 'Nilai',
                'NetTotal' => 'Total',
                'AmountDiscount' => 'Discount',
                'NetTotalInWords' => 'Terbilang',
            ],
        ],
    ],
];
